export const propertiesData = {
  "tiny-house": {
    slug: "tiny-house",
    title: "Tiny House",
    image: "/house-1.jpg",
    location: "Bukit Segar Avenue",
    rooms: "5",
    bathrooms: "3",
    type: "House",
    state: "Selangor",
    city: "Cheras",
    price: "RM 120,000",
  },
  "modern-villa": {
    slug: "modern-villa",
    title: "Modern Villa",
    image: "/house-2.jpg",
    location: "Taman Tun Dr Ismail",
    rooms: "6",
    bathrooms: "4",
    type: "Villa",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    price: "RM 2,300,000",
  },
  "beachside-bungalow": {
    slug: "beachside-bungalow",
    title: "Beachside Bungalow",
    image: "/apartment-1.jpg",
    location: "Pantai Cenang",
    rooms: "4",
    bathrooms: "2",
    type: "Bungalow",
    state: "Kedah",
    city: "Langkawi",
    price: "RM 950,000",
  },
  "urban-loft": {
    slug: "urban-loft",
    title: "Urban Loft",
    image: "/house-3.jpg",
    location: "Bangsar South",
    rooms: "3",
    bathrooms: "2",
    type: "Apartment",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    price: "RM 850,000",
  },
  "mountain-cabin": {
    slug: "mountain-cabin",
    title: "Mountain Cabin",
    image: "/apartment-2.jpg",
    location: "Cameron Highlands",
    rooms: "3",
    bathrooms: "1",
    type: "Cabin",
    state: "Pahang",
    city: "Cameron Highlands",
    price: "RM 650,000",
  },
  "heritage-home": {
    slug: "heritage-home",
    title: "Heritage Home",
    image: "/house-4.jpg",
    location: "Georgetown",
    rooms: "5",
    bathrooms: "3",
    type: "Terrace",
    state: "Penang",
    city: "George Town",
    price: "RM 1,200,000",
  },
  "riverside-cottage": {
    slug: "riverside-cottage",
    title: "Riverside Cottage",
    image: "/house-5.jpg",
    location: "Kuala Kangsar",
    rooms: "4",
    bathrooms: "2",
    type: "Cottage",
    state: "Perak",
    city: "Kuala Kangsar",
    price: "RM 780,000",
  },
  "city-penthouse": {
    slug: "city-penthouse",
    title: "City Penthouse",
    image: "/apartment-3.jpg",
    location: "KLCC",
    rooms: "3",
    bathrooms: "3",
    type: "Penthouse",
    state: "Kuala Lumpur",
    city: "Kuala Lumpur",
    price: "RM 4,500,000",
  },
  "eco-lodge": {
    slug: "eco-lodge",
    title: "Eco Lodge",
    image: "/apartment-4.jpg",
    location: "Sepang",
    rooms: "5",
    bathrooms: "3",
    type: "Lodge",
    state: "Selangor",
    city: "Sepang",
    price: "RM 1,050,000",
  },
  "forest-retreat": {
    slug: "forest-retreat",
    title: "Forest Retreat",
    image: "/apartment-5.jpg",
    location: "Fraser's Hill",
    rooms: "6",
    bathrooms: "4",
    type: "Retreat",
    state: "Pahang",
    city: "Raub",
    price: "RM 1,800,000",
  },
};
